BOARD_LIST = [
    ('ICSE', 'ICSE'),
    ('CBSE', 'CBSE'),
    ('NIOS', 'NIOS'),
    ('UP', 'UP'),
    ('JKBOSE', 'JKBOSE'),
    ('RBSE', 'RBSE'),
    ('HPBOSE', 'HPBOSE'),
    ('MPBSE', 'MPBSE'),
    ('CGBSE', 'CGBSE'),
    ('PSEB', 'PSEB'),
    ('BSEH', 'BSEH'),
    ('BSEB', 'BSEB'),
    ('GSEB', 'GSEB'),
    ('MSBSHSE', 'MSBSHSE'),
    ('BIEAP', 'BIEAP'),
    ('BSEAP', 'BSEAP'),
    ('WBBSE', 'WBBSE'),
    ('WBCHSE', 'WBCHSE'),
]
