GOALS_LIST = [('ACCOUNTANT', 'ACCOUNTANT'), ('ACTOR', 'ACTOR'), ('ARCHITECT', 'ARCHITECT'), ('ARTIST', 'ARTIST'),
              ('ASTRONAUT', 'ASTRONAUT'), ('ARMY', 'ARMY'), ('AUTHOR', 'AUTHOR'), ('CHEF', 'CHEF'),
              ('CYBERSECURITY', 'CYBERSECURITY'), ('DATA_SCIENTIST', 'DATA_SCIENTIST'), ('DESIGNER', 'DESIGNER'),
              ('DOCTOR', 'DOCTOR'), ('ENGINEER', 'ENGINEER'), ('JUDGE', 'JUDGE'), ('LAWYER', 'LAWYER'),
              ('MUSICIAN', 'MUSICIAN'), ('POLICE_OFFICER', 'POLICE_OFFICER'), ('PSYCHOLOGIST', 'PSYCHOLOGIST'),
              ('SCIENTIST', 'SCIENTIST'), ('SOFTWARE_DEVELOPER', 'SOFTWARE_DEVELOPER'), ('TEACHER', 'TEACHER')]
