# Generated by Django 3.2 on 2022-05-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teacher.classteacher', verbose_name='Class Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('ct', 'date')},
        ),
    ]
