# Generated by Django 3.2 on 2022-05-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSection', models.CharField(blank=True, choices=[('C_LKG_A', 'C_LKG_A'), ('C_LKG_B', 'C_LKG_B'), ('C_LKG_C', 'C_LKG_C'), ('C_LKG_D', 'C_LKG_D'), ('C_LKG_E', 'C_LKG_E'), ('C_UKG_A', 'C_UKG_A'), ('C_UKG_B', 'C_UKG_B'), ('C_UKG_C', 'C_UKG_C'), ('C_UKG_D', 'C_UKG_D'), ('C_UKG_E', 'C_UKG_E'), ('C_1_A', 'C_1_A'), ('C_1_B', 'C_1_B'), ('C_1_C', 'C_1_C'), ('C_1_D', 'C_1_D'), ('C_1_E', 'C_1_E'), ('C_2_A', 'C_2_A'), ('C_2_B', 'C_2_B'), ('C_2_C', 'C_2_C'), ('C_2_D', 'C_2_D'), ('C_2_E', 'C_2_E'), ('C_3_A', 'C_3_A'), ('C_3_B', 'C_3_B'), ('C_3_C', 'C_3_C'), ('C_3_D', 'C_3_D'), ('C_3_E', 'C_3_E'), ('C_4_A', 'C_4_A'), ('C_4_B', 'C_4_B'), ('C_4_C', 'C_4_C'), ('C_4_D', 'C_4_D'), ('C_4_E', 'C_4_E'), ('C_5_A', 'C_5_A'), ('C_5_B', 'C_5_B'), ('C_5_C', 'C_5_C'), ('C_5_D', 'C_5_D'), ('C_5_E', 'C_5_E'), ('C_6_A', 'C_6_A'), ('C_6_B', 'C_6_B'), ('C_6_C', 'C_6_C'), ('C_6_D', 'C_6_D'), ('C_6_E', 'C_6_E'), ('C_7_A', 'C_7_A'), ('C_7_B', 'C_7_B'), ('C_7_C', 'C_7_C'), ('C_7_D', 'C_7_D'), ('C_7_E', 'C_7_E'), ('C_8_A', 'C_8_A'), ('C_8_B', 'C_8_B'), ('C_8_C', 'C_8_C'), ('C_8_D', 'C_8_D'), ('C_8_E', 'C_8_E'), ('C_9_A', 'C_9_A'), ('C_9_B', 'C_9_B'), ('C_9_C', 'C_9_C'), ('C_9_D', 'C_9_D'), ('C_9_E', 'C_9_E'), ('C_10_A', 'C_10_A'), ('C_10_B', 'C_10_B'), ('C_10_C', 'C_10_C'), ('C_10_D', 'C_10_D'), ('C_10_E', 'C_10_E'), ('C_11_A', 'C_11_A'), ('C_11_B', 'C_11_B'), ('C_11_C', 'C_11_C'), ('C_11_D', 'C_11_D'), ('C_11_E', 'C_11_E'), ('C_12_A', 'C_12_A'), ('C_12_B', 'C_12_B'), ('C_12_C', 'C_12_C'), ('C_12_D', 'C_12_D'), ('C_12_E', 'C_12_E')], max_length=7, verbose_name='Class & Section')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact', models.CharField(max_length=10)),
                ('startedTeaching', models.IntegerField(verbose_name='Started Teaching')),
                ('joiningDate', models.DateField(verbose_name='Joining Date')),
                ('qualification', models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('BED', 'BED'), ('MED', 'MED'), ('MA', 'MA'), ('BA', 'BA'), ('DIPLOMA', 'DIPLOMA')], max_length=7)),
                ('about', models.TextField()),
                ('prev_school', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
            ],
        ),
    ]
